// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7: the CLI (migrate/db) uses this url. Migrations need the DIRECT
    // connection (5432) — the pooler at 6543 hangs migrations (hard rule #3).
    // The runtime client uses the POOLED DATABASE_URL, set in lib/db.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
